name: Python CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
    
    - name: Lint with flake8
      run: |
        # Controllo base della sintassi e errori evidenti
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # Controllo dello stile del codice (warning ma non errori)
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    
    - name: Run tests
      run: |
        cd foobar && python -m pytest test_foobar.py
        cd ../rock_paper_scissors && python -m pytest test_game.py 